web:
  build: .
  container_name: web_container
  ports:
    - "8080:8080"
  command: java -jar mvc-app.jar
  links:
    - db
db:
  container_name: mysql_container
  image: mysql
  environment:
    - MYSQL_DATABASE=events_demo
    - MYSQL_ROOT_PASSWORD=my-secret-pw
  ports:
    - "3306:3306"